train_data = """
Generative Pre-trained Transformer 2 (GPT-2)
Generative Pre-trained Transformer 2 (GPT-2) is a large language model by OpenAI and the second in their foundational series of GPT models. GPT-2 was pre-trained on a dataset of 8 million web pages.[2] It was partially released in February 2019, followed by full release of the 1.5-billion-parameter model on November 5, 2019.[3][4][5]

GPT-2 was created as a "direct scale-up" of GPT-1[6] with a ten-fold increase in both its parameter count and the size of its training dataset.[5] It is a general-purpose learner and its ability to perform the various tasks was a consequence of its general ability to accurately predict the next item in a sequence,[2][7] which enabled it to translate texts, answer questions about a topic from a text, summarize passages from a larger text,[7] and generate text output on a level sometimes indistinguishable from that of humans; however, it could become repetitive or nonsensical when generating long passages.[8] It was superseded by the GPT-3 and GPT-4 models, which are no longer open source.

GPT-2 has, like its predecessor GPT-1 and its successors GPT-3 and GPT-4, a generative pre-trained transformer architecture, implementing a deep neural network, specifically a transformer model,[6] which uses attention instead of older recurrence- and convolution-based architectures.[9][10] Attention mechanisms allow the model to selectively focus on segments of input text it predicts to be the most relevant.[11][12] This model allows for greatly increased parallelization, and outperforms previous benchmarks for RNN/CNN/LSTM-based models.[6]

Training
Since the transformer architecture enabled massive parallelization, GPT models could be trained on larger corpora than previous NLP (natural language processing) models. While the GPT-1 model demonstrated that the approach was viable, GPT-2 would further explore the emergent properties of networks trained on extremely large corpora. CommonCrawl, a large corpus produced by web crawling and previously used in training NLP systems,[13] was considered due to its large size, but was rejected after further review revealed large amounts of unintelligible content.[2][13] Instead, OpenAI developed a new corpus, known as WebText; rather than scraping content indiscriminately from the World Wide Web, WebText was generated by scraping only pages linked to by Reddit posts that had received at least 3 karma prior to December 2017. The corpus was subsequently cleaned; HTML documents were parsed into plain text, duplicate pages were eliminated, and Wikipedia pages were removed (since their presence in many other datasets could have induced overfitting).[2]

While the cost of training GPT-2 is known to have been $256 per hour,[14][15] the amount of hours it took to complete training is unknown; therefore, the overall training cost cannot be estimated accurately.[16] However, comparable large language models using transformer architectures have had their costs documented in more detail; the training processes for BERT and XLNet consumed, respectively, $6,912 and $245,000 of resources.[15]

Release
GPT-2 was first announced on 14 February 2019. A February 2019 article in The Verge by James Vincent said that, while "[the] writing it produces is usually easily identifiable as non-human", it remained "one of the most exciting examples yet" of language generation programs:[17]

Give it a fake headline, and it'll write the rest of the article, complete with fake quotations and statistics. Feed it the first line of a short story, and it'll tell you what happens to your character next. It can even write fan fiction, given the right prompt.[17]

The Guardian described this output as "plausible newspaper prose";[8] Kelsey Piper of Vox said "one of the coolest AI systems I've ever seen may also be the one that will kick me out of my job".[18] GPT-2's flexibility was described as "impressive" by The Verge; specifically, its ability to translate text between languages, summarize long articles, and answer trivia questions were noted.[17]

A study by the University of Amsterdam employing a modified Turing test found that at least in some scenarios, participants were unable to distinguish poems generated by GPT-2 from those written by humans.[19]

Restrictions and partial release
While previous OpenAI models had been made immediately available to the public, OpenAI initially refused to make a public release of GPT-2's source code when announcing it in February, citing the risk of malicious use;[8] limited access to the model (i.e. an interface that allowed input and provided output, not the source code itself) was allowed for selected press outlets on announcement.[8] One commonly-cited justification was that, since generated text was usually completely novel, it could be used by spammers to evade automated filters; OpenAI demonstrated a version of GPT-2 fine-tuned to "generate infinite positive – or negative – reviews of products".[8]

Another justification was that GPT-2 could be used to generate text that was obscene or racist. Researchers such as Jeremy Howard warned of "the technology to totally fill Twitter, email, and the web up with reasonable-sounding, context-appropriate prose, which would drown out all other speech and be impossible to filter".[17] The Allen Institute for Artificial Intelligence, in response to GPT-2, announced a tool to detect "neural fake news".[20]

However, opinion was divided. A February 2019 article in The Verge argued that the threat posed by GPT-2 had been exaggerated;[21] Anima Anandkumar, a professor at Caltech and director of machine learning research at Nvidia, said that there was no evidence that GPT-2 had the capabilities to pose the threats described by OpenAI, and that what they did was the "opposite of open", characterizing their refusal to release the full model as "malicious BS".[21] The Gradient published an open letter to OpenAI requesting that they release the model publicly, comparing the threat posed by text-generation AI to the threat posed by the printing press, and giving Photoshop as an example of "a technology that has (thankfully) not destroyed modern society despite its potential for chaos":[22]

Thirty years later, society has emerged relatively unscathed despite Photoshop being simple enough for high school students to use and ubiquitous enough to commandeer its own verb. Why? Precisely because everyone knows about Photoshop.[22]

774M release
While OpenAI did not release the fully-trained model or the corpora it was trained on, description of their methods in prior publications (and the free availability of underlying technology) made it possible for GPT-2 to be replicated by others as free software; one such replication, OpenGPT-2, was released in August 2019, in conjunction with a freely licensed version of WebText called OpenWebText. The cloud compute costs for OpenGPT-2 were given as approximately $50,000.[23]

On August 20, 2019, OpenAI released a partial version of GPT-2, with 774 million parameters (roughly half the size of the full 1.5 billion parameter model).[24]

Full 1.5B release
Initial concerns that GPT-2 would lend itself to widespread misuse did not come to pass; The Verge said that "there are reasons to be skeptical about claims that AI technology will usher in some sort of 'infopocalypse.' For a start, we already have programs that can generate plausible text at high volume for little cost: humans."[25] By November 2019, OpenAI said that they had "seen no strong evidence of misuse so far", and the full version, with 1.5 billion parameters trained with forty gigabytes of data, "about eight thousand times larger than the collected works of Shakespeare",[26] was released on November 5, 2019.[3][4]

Small and Medium Releases
Two other smaller releases of GPT-2 are available, including the small version of 124M parameters and the medium size of 355M parameters. Both are available to download from Huggingface.[27][28]

Limitations
While GPT-2's ability to generate plausible passages of natural language text were generally remarked on positively, its shortcomings were noted as well, especially when generating texts longer than a couple paragraphs; Vox said "the prose is pretty rough, there's the occasional non-sequitur, and the articles get less coherent the longer they get".[18] The Verge similarly noted that longer samples of GPT-2 writing tended to "stray off topic" and lack overall coherence;[17] The Register opined that "a human reading it should, after a short while, realize something's up", and noted that "GPT-2 doesn't answer questions as well as other systems that rely on algorithms to extract and retrieve information."[14]

GPT-2 deployment is resource-intensive; the full version of the model is larger than five gigabytes, making it difficult to embed locally into applications, and consumes large amounts of RAM. In addition, performing a single prediction "can occupy a CPU at 100% utilization for several minutes", and even with GPU processing, "a single prediction can take seconds". To alleviate these issues, the company Hugging Face created DistilGPT2, using knowledge distillation to produce a smaller model that "scores a few points lower on some quality benchmarks", but is "33% smaller and twice as fast".[citation needed]

Application and subsequent research
Even before the release of the full version, GPT-2 was used for a variety of applications and services, as well as for entertainment. In June 2019, a subreddit named r/SubSimulatorGPT2 was created in which a variety of GPT-2 instances trained on different subreddits made posts and replied to each other's comments, creating a situation where one could observe "an AI personification of r/Bitcoin argue with the machine learning-derived spirit of r/ShittyFoodPorn";[25] by July of that year, a GPT-2-based software program released to autocomplete lines of code in a variety of programming languages was described by users as a "game-changer".[29]

In 2019, AI Dungeon was launched, which used GPT-2 to generate dynamic text adventures based on user input.[30] AI Dungeon now offers access to the largest release of GPT-3 API as an optional paid upgrade, the free version of the site uses the 2nd largest release of GPT-3.[31] Latitude, the company formed around AI Dungeon, raised $3.3 million in seed funding in 2021.[32] Several websites host interactive demonstrations of different instances of GPT-2 and other transformer models.[33][34][35]

In February 2021, a crisis center for troubled teens announced that they would begin using a GPT-2-derived chatbot to help train counselors by allowing them to have conversations with simulated teens (this use was purely for internal purposes, and did not involve having GPT-2 communicate with the teens themselves).[36]

On May 9, 2023, OpenAI released a mapped version of GPT-2. OpenAI used successor model, GPT-4, to map each neuron of GPT-2 to determine their functions.[37]

Performance and evaluation
GPT-2 became capable of performing a variety of tasks beyond simple text production due to the breadth of its dataset and technique: answering questions, summarizing, and even translating between languages in a variety of specific domains, without being instructed in anything beyond how to predict the next word in a sequence.[17][18]

One example of generalized learning is GPT-2's ability to perform machine translation between French and English, for which task GPT-2's performance was assessed using WMT-14 translation tasks. GPT-2's training corpus included virtually no French text; non-English text was deliberately removed while cleaning the dataset prior to training, and as a consequence, only 10MB of French of the remaining 40,000MB was available for the model to learn from (mostly from foreign-language quotations in English posts and articles).[2]

Despite this, GPT-2 achieved 5 BLEU on the WMT-14 English-to-French test set (slightly below the score of a translation via word-for-word substitution). It was also able to outperform several contemporary (2017) unsupervised machine translation baselines on the French-to-English test set, where GPT-2 achieved 11.5 BLEU. This remained below the highest-performing contemporary unsupervised approach (2019), which had achieved 33.5 BLEU.[2] However, other models used large amounts of French text to achieve these results; GPT-2 was estimated to have used a monolingual French corpus approximately 1/500 the size of comparable approaches.[2]

GPT-2 was to be followed by the 175-billion-parameter GPT-3,[39] revealed to the public in 2020[40] (whose source code has never been made available). Access to GPT-3 is provided exclusively through APIs offered by OpenAI and Microsoft.[41] That was then later followed by GPT-4.

See also
Generative pre-trained transformer § Foundation models
References
"gpt-2". GitHub. Archived from the original on 11 March 2023. Retrieved 13 March 2023.
Radford, Alec; Wu, Jeffrey; Child, Rewon; Luan, David; Amodei, Dario; Sutskever, Ilua (14 February 2019). "Language models are unsupervised multitask learners" (PDF). OpenAI. 1 (8). Archived (PDF) from the original on 6 February 2021. Retrieved 19 December 2020.
Vincent, James (7 November 2019). "OpenAI has published the text-generating AI it said was too dangerous to share". The Verge. Archived from the original on 11 June 2020. Retrieved 19 December 2020.
"GPT-2: 1.5B Release". OpenAI. 2019-11-05. Archived from the original on 2019-11-14. Retrieved 2019-11-14.
"Better Language Models and Their Implications". OpenAI. 14 February 2019. Archived from the original on 19 December 2020. Retrieved 19 December 2020.
Radford, Alec; Narasimhan, Karthik; Salimans, Tim; Sutskever, Ilya (11 June 2018). "Improving Language Understanding by Generative Pre-Training" (PDF). OpenAI. p. 12. Archived (PDF) from the original on 26 January 2021. Retrieved 23 January 2021.
Hegde, Chaitra; Patil, Shrikumar (9 June 2020). "Unsupervised Paraphrase Generation using Pre-trained Language Models". arXiv:2006.05477 [cs.CL].
Hern, Alex (14 February 2019). "New AI fake text generator may be too dangerous to release, say creators". The Guardian. Archived from the original on 14 February 2019. Retrieved 19 December 2020.
Vaswani, Ashish; Shazeer, Noam; Parmar, Niki; Uszkoreit, Jakob; Jones, Llion; Gomez, Aidan N; Kaiser, Łukasz; Polosukhin, Illia (2017). "Attention is All you Need" (PDF). Advances in Neural Information Processing Systems. 30. Curran Associates, Inc.
Olah, Chris; Carter, Shan (8 September 2016). "Attention and Augmented Recurrent Neural Networks". Distill. 1 (9). doi:10.23915/distill.00001. Archived from the original on 22 December 2020. Retrieved 22 January 2021.
Bahdanau, Dzmitry; Cho, Kyunghyun; Bengio, Yoshua (1 September 2014). "Neural Machine Translation by Jointly Learning to Align and Translate". arXiv:1409.0473 [cs.CL].
Luong, Minh-Thang; Pham, Hieu; Manning, Christopher D. (17 August 2015). "Effective Approaches to Attention-based Neural Machine Translation". arXiv:1508.04025 [cs.CL].
Trinh, Trieu H.; Le, Quoc V. (7 Jun 2018). "A Simple Method for Commonsense Reasoning". arXiv:1806.02847 [cs.CL].
Quach, Katyanna (14 February 2019). "Roses are red, this is sublime: We fed OpenAI's latest chat bot a classic Reg headline". The Register. Archived from the original on 9 March 2021. Retrieved 27 February 2021.
"The Staggering Cost of Training SOTA AI Models". Synced. 27 June 2019. Archived from the original on 24 November 2020. Retrieved 27 February 2021.
Wiggers, Kyle (23 March 2020). "Google open-sources framework that reduces AI training costs by up to 80%". VentureBeat. Archived from the original on 26 November 2020. Retrieved 27 February 2021.
Vincent, James (14 February 2019). "OpenAI's new multitalented AI writes, translates, and slanders". The Verge. Archived from the original on 18 December 2020. Retrieved 19 December 2020.
Piper, Kelsey (14 February 2019). "An AI helped us write this article". Vox. Archived from the original on 8 November 2020. Retrieved 19 December 2020.
Köbis, Nils; Mossink, Luca D. (1 January 2021). "Artificial intelligence versus Maya Angelou: Experimental evidence that people cannot differentiate AI-generated from human-written poetry". Computers in Human Behavior. 114: 106553. doi:10.1016/j.chb.2020.106553. hdl:21.11116/0000-0007-13E5-1.
Schwartz, Oscar (4 July 2019). "Could 'fake text' be the next global political threat?". The Guardian. Archived from the original on 16 July 2019. Retrieved 16 July 2019.
Vincent, James (21 February 2019). "AI researchers debate the ethics of sharing potentially harmful programs". The Verge. Archived from the original on 9 February 2021. Retrieved 27 February 2021.
Zhang, Hugh (19 February 2019). "OpenAI: Please Open Source Your Language Model". The Gradient. Archived from the original on 28 January 2021. Retrieved 28 February 2021.
Gokaslan, Aaron; Cohen, Vanya; Pavlick, Ellie; Tellex, Stefanie (22 August 2019). "OpenGPT-2: We Replicated GPT-2 Because You Can Too". Noteworthy. Archived from the original on 29 April 2023. Retrieved 27 February 2021.
Johnson, Khari (20 August 2019). "OpenAI releases curtailed version of GPT-2 language model". VentureBeat. Archived from the original on 18 December 2020. Retrieved 19 December 2020.
Vincent, James (6 June 2019). "There's a subreddit populated entirely by AI personifications of other subreddits". The Verge. Archived from the original on 21 February 2021. Retrieved 27 February 2021.
Murati, Ermira (2022-04-13). "Language & Coding Creativity | American Academy of Arts and Sciences". www.amacad.org. Retrieved 2024-03-18.
"GPT-2 Small". Retrieved October 29, 2024.
GPT-2 Medium. "Openai-community/Gpt2-medium · Hugging Face".
Vincent, James (24 July 2019). "This AI-powered autocompletion software is Gmail's Smart Compose for coders". The Verge. Archived from the original on 9 March 2021. Retrieved 27 February 2021.
Olson, Mathew (17 December 2019). "AI Dungeon 2, the Text Adventure Where You Can do Nearly Anything, Is Now on Mobile". Archived from the original on 20 September 2020. Retrieved 27 February 2021.
Nelius, Joanna (3 August 2020). "This AI-Powered Choose-Your-Own-Adventure Text Game Is Super Fun and Makes No Sense". Gizmodo. Archived from the original on 28 February 2021. Retrieved 27 February 2021.
Ha, Anthony (4 February 2021). "AI Dungeon-maker Latitude raises $3.3M to build games with 'infinite' story possibilities". TechCrunch. Archived from the original on 21 February 2021. Retrieved 27 February 2021.
"Write With Transformer". Archived from the original on December 4, 2019. Retrieved December 4, 2019.
"Talk to Transformer". Archived from the original on December 4, 2019. Retrieved December 4, 2019.
"CreativeEngines". Archived from the original on February 3, 2023. Retrieved June 25, 2021.
Ohlheiser, Abby; Hao, Karen (26 February 2021). "An AI is training counselors to deal with teens in crisis". MIT Technology Review. Archived from the original on 27 February 2021. Retrieved 27 February 2021.
"Language models can explain neurons in language models". OpenAI. Retrieved 13 May 2023.
Zhu, Yukun; Kiros, Ryan; Zemel, Rich; Salakhutdinov, Ruslan; Urtasun, Raquel; Torralba, Antonio; Fidler, Sanja (2015). "Aligning Books and Movies: Towards Story-Like Visual Explanations by Watching Movies and Reading Books". International Conference on Computer Vision 2015: 19–27. arXiv:1506.06724. Archived from the original on 2023-02-05. Retrieved 2023-02-05.
Brown, Tom B.; Mann, Benjamin; Ryder, Nick; Subbiah, Melanie; Kaplan, Jared; Dhariwal, Prafulla; Neelakantan, Arvind; Shyam, Pranav; Sastry, Girish; Askell, Amanda; Agarwal, Sandhini; Herbert-Voss, Ariel; Krueger, Gretchen; Henighan, Tom; Child, Rewon; Ramesh, Aditya; Ziegler, Daniel M.; Wu, Jeffrey; Winter, Clemens; Hesse, Christopher; Chen, Mark; Sigler, Eric; Litwin, Mateusz; Gray, Scott; Chess, Benjamin; Clark, Jack; Berner, Christopher; McCandlish, Sam; Radford, Alec; Sutskever, Ilya; Amodei, Dario (July 22, 2020). "Language Models are Few-Shot Learners". arXiv:2005.14165 [cs.CL].
Arram (July 9, 2020). "GPT-3: An AI that's eerily good at writing almost anything". Arram Sabeti. Archived from the original on July 20, 2020. Retrieved July 31, 2020.
Hao, Karen (September 23, 2020). "OpenAI is giving Microsoft exclusive access to its GPT-3 language model". MIT Technology Review. Archived from the original on 2021-02-05. Retrieved 2020-09-25. The companies say OpenAI will continue to offer its public-facing API, which allows chosen users to send text to GPT-3 or OpenAI's other models and receive its output. Only Microsoft, however, will have access to GPT-3's underlying code, allowing it to embed, repurpose, and modify the model as it pleases.
"""

tokens = train_data.encode("utf-8")
tokens = list(map(int, tokens))
# print("Tokens:", tokens)
# print("Length of tokens:", len(tokens))



def get_token_pair_frequency(tokens):
    token_pair_frequency = {}
    for i in range(len(tokens) - 1):
        token_pair = (tokens[i], tokens[i + 1])
        if token_pair in token_pair_frequency:
            token_pair_frequency[token_pair] += 1
        else:
            token_pair_frequency[token_pair] = 1
    return token_pair_frequency
            
token_pairs = get_token_pair_frequency(tokens)
# print("Token pairs:", token_pairs)
# print("Sorted token pairs:", sorted(((v,k) for k,v in token_pairs.items()), reverse=True))
# print(chr(101))
# print(chr(32))

top_pair = max(token_pairs, key=token_pairs.get)
# print(top_pair)


def merge_tokens(ids,pair,idx):
  new_ids = []
  i = 0
  while i < len(ids):
    if i < len(ids) - 1 and ids[i] == pair[0] and ids[i+1] == pair[1]:
      new_ids.append(idx)
      i+= 2
    else:
      new_ids.append(ids[i])
      i+= 1
  return new_ids

# Trial merge
# print(merge_tokens([3,5,5,6,7], (5,6), 99))
  
# tokens2 = merge_tokens(tokens,top_pair, 256)
# print(tokens2)
# print("Length of tokens2:", len(tokens2))

vocab_size = 1000
num_merges = vocab_size - 256
ids = list(tokens)

merges = {}

for i in range(num_merges):
  token_pairs = get_token_pair_frequency(ids)
  top_pair = max(token_pairs, key=token_pairs.get)
  idx = 256 + i
  print(f"merging {top_pair} into a new token {idx}")
  ids = merge_tokens(ids, top_pair, idx)
  merges[top_pair] = idx

# print(ids)

compression_ration = len(tokens) / len(ids)

# print("Length of original text:", len(train_data))
# print("Length of old tokens:", len(tokens))
# print("Length of new tokens:", len(ids))
# print(f"Compression ratio: {compression_ration:.2f}x")

# DECODING
vocab = {idx: bytes([idx]) for idx in range(256)}  # A mapping from the token id to the raw bytes item for that token

for pair, idx in merges.items(): # Begin with the raw bytes pais from 0 - 255
  vocab[idx] = vocab[pair[0]] + vocab[pair[1]] # Merge the pair into a new token


def decode(ids):
  # given ids (list of token ids), return the decoded string
  tokens = b"".join(vocab[idx] for idx in ids)
  text = tokens.decode("utf-8", errors='replace')
  return text

# print(decode([128]))f

# ENCODING
def encode(text):
  tokens = list(text.encode("utf-8"))
  while len(tokens) > 1:
    token_frequency = get_token_pair_frequency(tokens)
    pair = min(token_frequency, key=lambda p: merges.get(p, float('inf')))
    if pair not in merges:
      break # Nothing else can be merged
    idx = merges[pair]
    tokens = merge_tokens(tokens, pair, idx)
  return tokens

# print(encode("hello, world!"))
# print(encode("H"))

valtext = "While tokenization itself preserves meaning perfectly, how LLMs process and interpret those tokens afterward is where compression of meaning and potential loss can occur. The neural network's internal representations of tokens are compressed, fuzzy, and contextual - and that's a different stage of processing after the lossless tokenization step."
valtext2 = decode(encode(valtext))
print(valtext2 == valtext)

# Save the tokenizer
import pickle
import json

def save_tokenizer(filepath):
    """Save the tokenizer to a file"""
    # Convert bytes to serializable format
    serializable_vocab = {}
    for idx, byte_val in vocab.items():
        serializable_vocab[idx] = list(byte_val)
    
    tokenizer_data = {
        'merges': merges,
        'vocab': serializable_vocab
    }
    
    with open(filepath, 'wb') as f:
        pickle.dump(tokenizer_data, f)
    print(f"Tokenizer saved to {filepath}")

def load_tokenizer(filepath):
    """Load the tokenizer from a file"""
    with open(filepath, 'rb') as f:
        tokenizer_data = pickle.load(f)
    
    # Convert serialized format back to bytes
    loaded_vocab = {}
    for idx, byte_list in tokenizer_data['vocab'].items():
        loaded_vocab[idx] = bytes(byte_list)
    
    loaded_merges = tokenizer_data['merges']
    
    # Return the encoder and decoder functions that use the loaded vocab and merges
    def loaded_encode(text):
        tokens = list(text.encode("utf-8"))
        while len(tokens) > 1:
            token_frequency = get_token_pair_frequency(tokens)
            pair = min(token_frequency, key=lambda p: loaded_merges.get(p, float('inf')))
            if pair not in loaded_merges:
                break
            idx = loaded_merges[pair]
            tokens = merge_tokens(tokens, pair, idx)
        return tokens
    
    def loaded_decode(ids):
        tokens = b"".join(loaded_vocab[idx] for idx in ids)
        text = tokens.decode("utf-8", errors='replace')
        return text
        
    return loaded_encode, loaded_decode

# Example usage
if __name__ == "__main__":
    # Save the tokenizer
    save_tokenizer("tokenizer.pkl")
    
    # Test loading and using the tokenizer
    print("\nTesting loaded tokenizer:")
    loaded_encode, loaded_decode = load_tokenizer("tokenizer.pkl")
    
    test_text = "Testing the deployed tokenizer!"
    encoded = loaded_encode(test_text)
    decoded = loaded_decode(encoded)
    
    print(f"Original: {test_text}")
    print(f"Encoded: {encoded}")
    print(f"Decoded: {decoded}")
    print(f"Match: {test_text == decoded}")
    

# To deploy as a module:
# 1. Move these functions to a separate file like tokenizer.py
# 2. Import and use as needed in your applications
            
